// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgtm82Cg_zUsOTWrZgLWq1cFxyL_ZLhv0',
    appId: '1:180087486644:web:e64f66994efed606eeffe1',
    messagingSenderId: '180087486644',
    projectId: 'samar-portfolio-14cf1',
    authDomain: 'samar-portfolio-14cf1.firebaseapp.com',
    storageBucket: 'samar-portfolio-14cf1.firebasestorage.app',
    measurementId: 'G-F0LMN9J63H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ8OzDXn1AW54RxiIxMQ0J0Sr9b_nA93M',
    appId: '1:180087486644:android:ea81b8103c408a8feeffe1',
    messagingSenderId: '180087486644',
    projectId: 'samar-portfolio-14cf1',
    storageBucket: 'samar-portfolio-14cf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFpEybtGz04KqYthclYroNd16d1fYXm5I',
    appId: '1:180087486644:ios:980ead01c1c951aaeeffe1',
    messagingSenderId: '180087486644',
    projectId: 'samar-portfolio-14cf1',
    storageBucket: 'samar-portfolio-14cf1.firebasestorage.app',
    iosBundleId: 'com.example.samarPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFpEybtGz04KqYthclYroNd16d1fYXm5I',
    appId: '1:180087486644:ios:980ead01c1c951aaeeffe1',
    messagingSenderId: '180087486644',
    projectId: 'samar-portfolio-14cf1',
    storageBucket: 'samar-portfolio-14cf1.firebasestorage.app',
    iosBundleId: 'com.example.samarPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFb3wWxO2Sw6K2NcmEF4ODAVW2iwrlmWk',
    appId: '1:180087486644:web:8dedf09b3ac4bde6eeffe1',
    messagingSenderId: '180087486644',
    projectId: 'samar-portfolio-14cf1',
    authDomain: 'samar-portfolio-14cf1.firebaseapp.com',
    storageBucket: 'samar-portfolio-14cf1.firebasestorage.app',
    measurementId: 'G-ZPFFP9MJ3H',
  );
}
